project:
    type: book
    output-dir: _site

book:
    chapters:
    - index.qmd
    - part: "Curso"
      chapters:
        - room/chapters/physicschaos.qmd
        - room/chapters/pendulum.qmd
        - room/chapters/phasespace.qmd
        - room/chapters/initialconditions.qmd
        - room/chapters/orbits.qmd
    - part: room/chapters/hamiltonian/flux.qmd
      chapters:
        - room/chapters/hamiltonian/liuville.qmd
        - room/chapters/hamiltonian/symplect.qmd
        
    - part: room/chapters/integradores/integrators.qmd
      chapters:
        - room/chapters/integradores/verlet.qmd
        - room/chapters/integradores/forestruth.qmd
        - room/chapters/integradores/tao.qmd
        - room/chapters/integradores/symplecf.qmd
    search:
        location: navbar
        type: textbox 
    sidebar:
        style: docked
    navbar:
        logo: "https://assets.tmfss.net/logos/IbitiPhysIcoGrey.svg"


        title: "Sistemas Caóticos"
        search: true # Cria a barra de pesquisa (Search) automaticamente
        left:
            - text: "Home"
              href: index.qmd
            - text: "Features"
              href: features.qmd # Troque para os nomes dos seus arquivos reais
            - text: "Pricing"
              href: pricing.qmd
            - text: "About"
              href: about.qmd
            - text: "Dropdown" # Exemplo de Menu Dropdown
              menu:
                - text: "Action"
                  href: action.qmd
                - text: "Another action"
                  href: another.qmd
                - "---" # Cria a linha separadora (dropdown-divider)
                - text: "Separated link"
                  href: separated.qmd
        right:
            - icon: easel # Ícone de um quadro de apresentação (alternativas: 'projector' ou 'display')
              href: https://chaosminicurse.tmfss.net/slides # Aqui você coloca o link de saída do seu Reveal.js
              #title: "Slides do Minicurso"
              #aria-label: "Apresentação"
            - text: "|" # Nossa primeira barrinha divisória
            - icon: github # Puxa a logo do GitHub automaticamente
              href: https://github.com/tmfss/ChaoticSystems
              target: _blank
              #title: "Código Fonte (GitHub)"
              #aria-label: "GitHub"
            - text: "|" # Nossa segunda barrinha divisória
            - icon: circle-half
              menu:
                - text: "Light"
                  icon: sun
                  href: "javascript:void(0)" 
                - text: "Dark"
                  icon: moon-stars
                  href: "javascript:void(0)" 
            - text: " " # Nossa segunda barrinha divisória